### ISSUE TITLE
Add check for existence of tests symlink in testWithXrun task

### ISSUE THREAD

**Issue by odiaz94** [tudortimi/gradle-hdvl#92]
On multiple runs displays this:
``` Could not create 'tests' link ```
Likely referring to the symlink in build/svunit

**Comment by tudortimi** [comment]
This is the code that prints the message:
https://github.com/tudortimi/gradle-hdvl/blob/1538eb6f5c0a30862f17caba8340ffef1e8543e8/src/main/java/com/verificationgentleman/gradle/hdvl/svunit/TestTask.java#L97-L102

No idea what visionary thoughts I had when I caught the exception and just printed a message. I'm not sure whether I wanted to ignore the exception or make this an error later on. In any case, the code should remove and re-link, ideally in the same operation.

**Comment by tudortimi** [comment]
It seems that the idiom is to delete if it exists and create the link:

https://www.baeldung.com/java-symlink#creatingLinks
https://stackoverflow.com/questions/33250193/files-createsymboliclink-java-nio-file-doesnt-override-existing-symbol-link

**Comment by tudortimi** [comment]
This isn't just an annoyance. If the `tests` link exists and points to some other location that where it should, it will cause the task to fail, because it won't be passing the proper tests to SVUnit.
